# Generated by Django 4.2.25 on 2025-10-22 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True
	
	dependencies = [
		('core', '0001_initial'),
	]
	
	operations = [
		migrations.CreateModel(
			name='DataSource',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=255)),
				('source_type', models.CharField(max_length=64)),
				('config', models.JSONField(blank=True, default=dict)),
				('is_active', models.BooleanField(default=True)),
				('organization',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources',
				                   to='core.organization')),
			],
		),
		migrations.CreateModel(
			name='Report',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=255)),
				('definition', models.JSONField(blank=True, default=dict)),
				('schedule_cron', models.CharField(blank=True, max_length=64)),
				('last_run_at', models.DateTimeField(blank=True, null=True)),
				('last_run_status', models.CharField(default='never', max_length=32)),
				('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports',
				                                   to='core.organization')),
			],
		),
		migrations.CreateModel(
			name='ModelTrainingRun',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('model_type', models.CharField(max_length=64)),
				('status', models.CharField(default='pending', max_length=32)),
				('parameters', models.JSONField(blank=True, default=dict)),
				('metrics', models.JSONField(blank=True, default=dict)),
				('started_at', models.DateTimeField(auto_now_add=True)),
				('completed_at', models.DateTimeField(blank=True, null=True)),
				('organization',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_runs',
				                   to='core.organization')),
			],
		),
		migrations.CreateModel(
			name='Insight',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('title', models.CharField(max_length=255)),
				('description', models.TextField(blank=True)),
				('severity', models.CharField(default='info', max_length=32)),
				('data', models.JSONField(blank=True, default=dict)),
				('detected_at', models.DateTimeField(auto_now_add=True)),
				('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights',
				                                   to='core.organization')),
			],
		),
		migrations.CreateModel(
			name='Forecast',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=255)),
				('target', models.CharField(max_length=128)),
				('horizon_days', models.PositiveIntegerField(default=30)),
				('configuration', models.JSONField(blank=True, default=dict)),
				('result', models.JSONField(blank=True, default=dict)),
				('generated_at', models.DateTimeField(auto_now_add=True)),
				('organization',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts',
				                   to='core.organization')),
			],
		),
		migrations.CreateModel(
			name='DataSyncLog',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('status', models.CharField(max_length=32)),
				('started_at', models.DateTimeField(auto_now_add=True)),
				('completed_at', models.DateTimeField(blank=True, null=True)),
				('stats', models.JSONField(blank=True, default=dict)),
				('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs',
				                                  to='analytics.datasource')),
			],
		),
		migrations.CreateModel(
			name='Dashboard',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=255)),
				('layout', models.JSONField(blank=True, default=dict)),
				('filters', models.JSONField(blank=True, default=dict)),
				('organization',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards',
				                   to='core.organization')),
			],
		),
		migrations.CreateModel(
			name='CustomerSegment',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=255)),
				('description', models.TextField(blank=True)),
				('filter_definition', models.JSONField(blank=True, default=dict)),
				('size', models.PositiveIntegerField(default=0)),
				('ltv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
				('churn_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments',
				                                   to='core.organization')),
			],
		),
		migrations.CreateModel(
			name='MetricDefinition',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('code', models.CharField(max_length=64)),
				('name', models.CharField(max_length=255)),
				('description', models.TextField(blank=True)),
				('query', models.TextField(help_text='SQL or DSL definition of the metric')),
				('is_active', models.BooleanField(default=True)),
				('organization',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_definitions',
				                   to='core.organization')),
			],
			options={
				'ordering': ['code'],
				'unique_together': {('organization', 'code')},
			},
		),
	]
