# Generated by Django 4.2.25 on 2025-10-22 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True
	
	dependencies = [
		('core', '0001_initial'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]
	
	operations = [
		migrations.CreateModel(
			name='Category',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=255)),
				('slug', models.SlugField(max_length=255)),
				('organization',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories',
				                   to='core.organization')),
				('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
				                             related_name='children', to='catalog.category')),
			],
			options={
				'ordering': ['name'],
				'unique_together': {('organization', 'slug')},
			},
		),
		migrations.CreateModel(
			name='Product',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=255)),
				('sku', models.CharField(max_length=64)),
				('description', models.TextField(blank=True)),
				('is_active', models.BooleanField(default=True)),
				('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
				                               related_name='products', to='catalog.category')),
				('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products',
				                                   to='core.organization')),
			],
			options={
				'ordering': ['name'],
				'unique_together': {('organization', 'sku')},
			},
		),
		migrations.CreateModel(
			name='Supplier',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=255)),
				('contact_email', models.EmailField(blank=True, max_length=254)),
				('phone_number', models.CharField(blank=True, max_length=32)),
				('notes', models.TextField(blank=True)),
				('organization',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers',
				                   to='core.organization')),
			],
		),
		migrations.CreateModel(
			name='ProductVariant',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=255)),
				('sku', models.CharField(max_length=64)),
				('attributes', models.JSONField(blank=True, default=dict)),
				('price', models.DecimalField(decimal_places=2, max_digits=10)),
				('cost', models.DecimalField(decimal_places=2, max_digits=10)),
				('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants',
				                              to='catalog.product')),
			],
			options={
				'unique_together': {('product', 'sku')},
			},
		),
		migrations.CreateModel(
			name='PriceHistory',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('price', models.DecimalField(decimal_places=2, max_digits=10)),
				('currency', models.CharField(default='USD', max_length=8)),
				('recorded_at', models.DateTimeField(auto_now_add=True)),
				('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
				                                  to=settings.AUTH_USER_MODEL)),
				('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history',
				                              to='catalog.productvariant')),
			],
			options={
				'ordering': ['-recorded_at'],
			},
		),
		migrations.CreateModel(
			name='InventoryLot',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('quantity', models.PositiveIntegerField()),
				('received_at', models.DateField()),
				('expires_at', models.DateField(blank=True, null=True)),
				('location', models.CharField(blank=True, max_length=255)),
				('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
				                               related_name='inventory_lots', to='catalog.supplier')),
				('variant',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_lots',
				                   to='catalog.productvariant')),
			],
		),
	]
