# Generated by Django 4.2.25 on 2025-10-24 11:23

from django.db import migrations, models
import simplycrm.catalog.validators


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="main_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="product-images/",
                validators=[simplycrm.catalog.validators.validate_image_mime],
            ),
        ),
    ]
