# Generated by Django 4.2.25 on 2025-10-24 11:29

from django.db import migrations
import simplycrm.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_plans"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", simplycrm.core.models.OrganizationAwareUserManager()),
            ],
        ),
    ]
