# Generated by Django 4.2.25 on 2025-10-26 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['price_per_month', 'pk']},
        ),
    ]
