# Generated by Django 4.2.25 on 2025-10-22 20:50

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True
	
	dependencies = [
		('catalog', '0001_initial'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		('core', '0001_initial'),
	]
	
	operations = [
		migrations.CreateModel(
			name='Company',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=255)),
				('industry', models.CharField(blank=True, max_length=128)),
				('website', models.URLField(blank=True)),
				('billing_address', models.TextField(blank=True)),
				('shipping_address', models.TextField(blank=True)),
				('organization',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies',
				                   to='core.organization')),
			],
		),
		migrations.CreateModel(
			name='Contact',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('first_name', models.CharField(max_length=128)),
				('last_name', models.CharField(max_length=128)),
				('email', models.EmailField(blank=True, max_length=254)),
				('phone_number', models.CharField(blank=True, max_length=32)),
				('tags', models.JSONField(blank=True, default=list)),
				('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
				                              related_name='contacts', to='sales.company')),
				('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts',
				                                   to='core.organization')),
			],
		),
		migrations.CreateModel(
			name='DealStage',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=255)),
				('position', models.PositiveIntegerField(default=0)),
				('win_probability', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5)),
			],
			options={
				'ordering': ['position'],
			},
		),
		migrations.CreateModel(
			name='Invoice',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('issued_at', models.DateTimeField(auto_now_add=True)),
				('due_date', models.DateField(blank=True, null=True)),
				('status', models.CharField(default='draft', max_length=32)),
				('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
			],
		),
		migrations.CreateModel(
			name='Lead',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('source', models.CharField(blank=True, max_length=128)),
				('status', models.CharField(default='new', max_length=64)),
				('notes', models.TextField(blank=True)),
				('score', models.IntegerField(default=0)),
				('metadata', models.JSONField(blank=True, default=dict)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
				                              related_name='leads', to='sales.contact')),
				('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads',
				                                   to='core.organization')),
			],
		),
		migrations.CreateModel(
			name='Opportunity',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=255)),
				('amount', models.DecimalField(decimal_places=2, max_digits=12)),
				('close_date', models.DateField(blank=True, null=True)),
				('probability', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5)),
				('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
				                           related_name='opportunities', to='sales.lead')),
				('organization',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities',
				                   to='core.organization')),
				('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
				                            to=settings.AUTH_USER_MODEL)),
			],
		),
		migrations.CreateModel(
			name='Order',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('status', models.CharField(default='draft', max_length=64)),
				('currency', models.CharField(default='USD', max_length=8)),
				('ordered_at', models.DateTimeField(auto_now_add=True)),
				('fulfilled_at', models.DateTimeField(blank=True, null=True)),
				('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
				                              related_name='orders', to='sales.contact')),
				('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
				                                  related_name='orders', to='sales.opportunity')),
				('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders',
				                                   to='core.organization')),
			],
		),
		migrations.CreateModel(
			name='Shipment',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('carrier', models.CharField(max_length=64)),
				('tracking_number', models.CharField(blank=True, max_length=128)),
				('shipped_at', models.DateTimeField(blank=True, null=True)),
				('delivered_at', models.DateTimeField(blank=True, null=True)),
				('status', models.CharField(default='pending', max_length=32)),
				('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments',
				                            to='sales.order')),
			],
		),
		migrations.CreateModel(
			name='Pipeline',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=255)),
				('organization',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines',
				                   to='core.organization')),
			],
		),
		migrations.CreateModel(
			name='Payment',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('amount', models.DecimalField(decimal_places=2, max_digits=12)),
				('provider', models.CharField(max_length=64)),
				('transaction_reference', models.CharField(max_length=128)),
				('processed_at', models.DateTimeField(auto_now_add=True)),
				('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments',
				                              to='sales.invoice')),
			],
		),
		migrations.CreateModel(
			name='OrderLine',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('quantity', models.PositiveIntegerField()),
				('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
				('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
				('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines',
				                            to='sales.order')),
				('product_variant',
				 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
			],
		),
		migrations.AddField(
			model_name='opportunity',
			name='pipeline',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities',
			                        to='sales.pipeline'),
		),
		migrations.AddField(
			model_name='opportunity',
			name='stage',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities',
			                        to='sales.dealstage'),
		),
		migrations.CreateModel(
			name='Note',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('content', models.TextField()),
				('related_object_type', models.CharField(max_length=64)),
				('related_object_id', models.PositiveIntegerField()),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
				                             to=settings.AUTH_USER_MODEL)),
				('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes',
				                                   to='core.organization')),
			],
		),
		migrations.AddField(
			model_name='invoice',
			name='order',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices',
			                        to='sales.order'),
		),
		migrations.AddField(
			model_name='dealstage',
			name='pipeline',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages',
			                        to='sales.pipeline'),
		),
		migrations.CreateModel(
			name='DealActivity',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('type', models.CharField(max_length=64)),
				('subject', models.CharField(max_length=255)),
				('notes', models.TextField(blank=True)),
				('due_at', models.DateTimeField(blank=True, null=True)),
				('completed_at', models.DateTimeField(blank=True, null=True)),
				('opportunity',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities',
				                   to='sales.opportunity')),
				('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
				                            to=settings.AUTH_USER_MODEL)),
			],
			options={
				'ordering': ['-due_at'],
			},
		),
		migrations.CreateModel(
			name='Attachment',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('file_name', models.CharField(max_length=255)),
				('file_url', models.URLField()),
				('related_object_type', models.CharField(max_length=64)),
				('related_object_id', models.PositiveIntegerField()),
				('uploaded_at', models.DateTimeField(auto_now_add=True)),
				('organization',
				 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments',
				                   to='core.organization')),
				('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
				                                  to=settings.AUTH_USER_MODEL)),
			],
		),
		migrations.AlterUniqueTogether(
			name='dealstage',
			unique_together={('pipeline', 'name')},
		),
	]
