# Generated by Django 4.2.25 on 2025-10-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
